/**
 *
 * Classe que gera a interface gráfica do programa
 * 
 * @author barcelosluan
 */

package tela;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import acesso.AcessoDados;
import cadastroPacientes.Paciente;
import cadastroPacientes.TableModel;

public class TelaPrincipal extends javax.swing.JFrame {

    private Paciente objPaciente;
    private AcessoDados objDAO;
    private boolean buscar = false;
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
        //Centralizando a janela
        this.setLocationRelativeTo(null);
        // Impede que a janela seja redimencionada 
        this.setResizable(false);
        // Variavel con recebendo a conexao
        carregarTable(null);
    }
    
    // Metodo que realiza conexao com o banco, faz uma instrucao Query(select)
    // para jogar na JTable atraves do modelo de tabela (ModelTabel.java)
    public void carregarTable(Paciente objPaciente) {

        objDAO = new AcessoDados();
        ArrayList dados = new ArrayList();
        if (buscar) {
            dados = objDAO.buscar(objPaciente);
        } else {
            objPaciente = new Paciente();
            dados = objDAO.listarTodos();
        }
        String[] colunas = objPaciente.getPacienteColunas();

        TableModel modelo = new TableModel(dados, colunas);

        tblPacientes.setModel(modelo);
        tblPacientes.getColumnModel().getColumn(0).setPreferredWidth(80);
        tblPacientes.getColumnModel().getColumn(0).setResizable(false);
        tblPacientes.getColumnModel().getColumn(1).setPreferredWidth(120);
        tblPacientes.getColumnModel().getColumn(1).setResizable(false);
        tblPacientes.getColumnModel().getColumn(2).setPreferredWidth(250);
        tblPacientes.getColumnModel().getColumn(2).setResizable(false);
        tblPacientes.getTableHeader().setReorderingAllowed(false);
    }
    
    // Metodo responsavel por selecionar um registro ao clicar ou seguir com as setas do teclado
    // na JTable, e realizar a vinculacao do mesmo nos TextFields
    public void selectRegistryTable() {

        txtPacienteID.setText(tblPacientes.getValueAt(tblPacientes.getSelectedRow(), 0).toString());

        //Object objNome = tblPacientes.getValueAt(tblPacientes.getSelectedRow(), 1);
        txtPacienteNome.setText(tblPacientes.getValueAt(tblPacientes.getSelectedRow(), 1).toString());
        txtPacienteCPF.setText(tblPacientes.getValueAt(tblPacientes.getSelectedRow(), 2).toString());
        txtPacienteMae.setText(tblPacientes.getValueAt(tblPacientes.getSelectedRow(), 3).toString());
        txtPacienteTelefone.setText(tblPacientes.getValueAt(tblPacientes.getSelectedRow(), 4).toString());
        txtPacienteInternacao.setText(tblPacientes.getValueAt(tblPacientes.getSelectedRow(), 5).toString());
        txtPacienteAlta.setText(tblPacientes.getValueAt(tblPacientes.getSelectedRow(), 6).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelDados = new javax.swing.JPanel();
        btnLimpar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPacienteID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPacienteNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPacienteCPF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPacienteMae = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPacienteTelefone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPacienteInternacao = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPacienteAlta = new javax.swing.JTextField();
        btnTestarConexao = new javax.swing.JButton();
        painelDB = new javax.swing.JPanel();
        painelDBRedimensionar = new javax.swing.JScrollPane();
        tblPacientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Pacientes");
        setResizable(false);

        painelDados.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        txtPacienteID.setEditable(false);
        txtPacienteID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPacienteIDActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome Completo");

        txtPacienteNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPacienteNomeActionPerformed(evt);
            }
        });

        jLabel3.setText("CPF");

        jLabel4.setText("Nome da Mãe");

        jLabel5.setText("Telefone Contato");

        jLabel6.setText("Data Internação");

        jLabel7.setText("Data da Alta");

        btnTestarConexao.setText("Testar Conexão");
        btnTestarConexao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestarConexaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelDadosLayout = new javax.swing.GroupLayout(painelDados);
        painelDados.setLayout(painelDadosLayout);
        painelDadosLayout.setHorizontalGroup(
            painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtPacienteNome))
                    .addGroup(painelDadosLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtPacienteMae))
                    .addGroup(painelDadosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPacienteID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDadosLayout.createSequentialGroup()
                        .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painelDadosLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtPacienteAlta))
                            .addGroup(painelDadosLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtPacienteInternacao))
                            .addGroup(painelDadosLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtPacienteTelefone))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelDadosLayout.createSequentialGroup()
                                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(painelDadosLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPacienteCPF))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelDadosLayout.createSequentialGroup()
                                        .addComponent(btnSalvar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnLimpar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDeletar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSair)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTestarConexao)
                .addGap(131, 131, 131))
        );
        painelDadosLayout.setVerticalGroup(
            painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPacienteID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPacienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPacienteCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPacienteMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPacienteTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPacienteInternacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPacienteAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(btnTestarConexao)
                .addGap(18, 18, 18)
                .addGroup(painelDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar)
                    .addComponent(btnSalvar)
                    .addComponent(btnSair)
                    .addComponent(btnDeletar)
                    .addComponent(btnBuscar))
                .addContainerGap())
        );

        painelDB.setBorder(javax.swing.BorderFactory.createTitledBorder("Pacientes Cadastrados"));

        tblPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "Mãe", "Telefone", "Internação", "Alta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPacientesMouseClicked(evt);
            }
        });
        painelDBRedimensionar.setViewportView(tblPacientes);
        if (tblPacientes.getColumnModel().getColumnCount() > 0) {
            tblPacientes.getColumnModel().getColumn(0).setResizable(false);
            tblPacientes.getColumnModel().getColumn(0).setPreferredWidth(20);
            tblPacientes.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblPacientes.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblPacientes.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblPacientes.getColumnModel().getColumn(4).setPreferredWidth(50);
            tblPacientes.getColumnModel().getColumn(5).setPreferredWidth(100);
            tblPacientes.getColumnModel().getColumn(6).setPreferredWidth(100);
            tblPacientes.getColumnModel().getColumn(6).setHeaderValue("Alta");
        }

        javax.swing.GroupLayout painelDBLayout = new javax.swing.GroupLayout(painelDB);
        painelDB.setLayout(painelDBLayout);
        painelDBLayout.setHorizontalGroup(
            painelDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelDBRedimensionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelDBLayout.setVerticalGroup(
            painelDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDBLayout.createSequentialGroup()
                .addComponent(painelDBRedimensionar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painelDB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        objPaciente = new Paciente();
        objPaciente.setPacienteId(txtPacienteID.getText());
        objPaciente.setPacienteNome(txtPacienteNome.getText());
        objPaciente.setPacienteCpf(txtPacienteCPF.getText());
        objPaciente.setPacienteMae(txtPacienteMae.getText());
        objPaciente.setPacienteTelefone(txtPacienteTelefone.getText());
        objPaciente.setPacienteInternacao(txtPacienteInternacao.getText());
        objPaciente.setPacienteAlta(txtPacienteAlta.getText());

        // fazendo a validação dos dados
        if ((txtPacienteNome.getText().isEmpty()) ||
                (txtPacienteCPF.getText().isEmpty()) ||
                (txtPacienteMae.getText().isEmpty()) ||
                (txtPacienteTelefone.getText().isEmpty()) ||
                (txtPacienteInternacao.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Informe valores para os campos");
        } else {
            // instanciando a classe AcessoDados do pacote dao e criando seu objeto dao
            objDAO = new AcessoDados();
            objDAO.salvar(objPaciente);
            JOptionPane.showMessageDialog(null, "Paciente " + txtPacienteNome.getText() + " inserido com sucesso! ");
        }

        carregarTable(null);

        // apaga os dados preenchidos nos campos de texto
        setClear();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        setClear();
        carregarTable(null);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        objPaciente.setPacienteId(txtPacienteID.getText());

        // fazendo a validação dos dados
        if ((txtPacienteID.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Informe valores para os campos");
        } else {
            // instanciando a classe AcessoDados do pacote dao e criando seu objeto dao
            objDAO = new AcessoDados();
            objDAO.deletar(objPaciente);
            JOptionPane.showMessageDialog(null, "Paciente Removido com Sucesso! ");
        }

        carregarTable(null);

        // apaga os dados preenchidos nos campos de texto
        setClear();
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        objPaciente = new Paciente();
        objPaciente.setPacienteNome(txtPacienteNome.getText());
        objPaciente.setPacienteCpf(txtPacienteCPF.getText());

        // fazendo a validação dos dados
        if ((!txtPacienteNome.getText().isEmpty()) || (!txtPacienteCPF.getText().isEmpty())) {
            // instanciando a classe AcessoDados do pacote dao e criando seu objeto dao
            objDAO = new AcessoDados();
            buscar = true;
            carregarTable(objPaciente);
        }else{
            buscar = false;
            carregarTable(null);
        }

        // apaga os dados preenchidos nos campos de texto
        setClear();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtPacienteIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPacienteIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPacienteIDActionPerformed

    private void txtPacienteNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPacienteNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPacienteNomeActionPerformed

    private void btnTestarConexaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestarConexaoActionPerformed
        try {
            AcessoDados.testarConexao();
        } catch (SQLException ex) {
            ex.getMessage();
        }

    }//GEN-LAST:event_btnTestarConexaoActionPerformed

    private void tblPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPacientesMouseClicked
        selectRegistryTable();
    }//GEN-LAST:event_tblPacientesMouseClicked
    
    public void setClear() {
        txtPacienteID.setText(null);
        txtPacienteNome.setText(null);
        txtPacienteCPF.setText(null);
        txtPacienteMae.setText(null);
        txtPacienteTelefone.setText(null);
        txtPacienteInternacao.setText(null);
        txtPacienteAlta.setText(null);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Dracula".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnTestarConexao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel painelDB;
    private javax.swing.JScrollPane painelDBRedimensionar;
    private javax.swing.JPanel painelDados;
    private javax.swing.JTable tblPacientes;
    private javax.swing.JTextField txtPacienteAlta;
    private javax.swing.JTextField txtPacienteCPF;
    private javax.swing.JTextField txtPacienteID;
    private javax.swing.JTextField txtPacienteInternacao;
    private javax.swing.JTextField txtPacienteMae;
    private javax.swing.JTextField txtPacienteNome;
    private javax.swing.JTextField txtPacienteTelefone;
    // End of variables declaration//GEN-END:variables
}
