import java.io.File;
  
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
  
import net.sourceforge.tess4j.Tesseract;
import net.sourceforge.tess4j.TesseractException;
  
public class FTesseractApp extends javax.swing.JFrame {
     
    /** Creates new form FTesseractApp */
    public FTesseractApp() {
        initComponents();
    }
     
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Gerado ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jTextFieldImagem = new javax.swing.JTextField();
        jButtonSelecionarImagem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOCR = new javax.swing.JTextArea();
  
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jLabel1.setText("Imagem");
  
        jTextFieldImagem.setEnabled(false);
  
        jButtonSelecionarImagem.setText("Carregar Imagem");
        jButtonSelecionarImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarImagemActionPerformed(evt);
            }
        });
  
        jLabel2.setText("Texto");
  
        jTextAreaOCR.setColumns(20);
        jTextAreaOCR.setRows(5);
        jScrollPane1.setViewportView(jTextAreaOCR);
  
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSelecionarImagem)
                    .addComponent(jTextFieldImagem, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButtonSelecionarImagem)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void jButtonSelecionarImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarImagemActionPerformed
       iniciarProcessamento();
    }//GEN-LAST:event_jButtonSelecionarImagemActionPerformed
     
       public void iniciarProcessamento() {
             try {
                    JFileChooser file = new JFileChooser();
                    file.setFileSelectionMode(JFileChooser.FILES_ONLY);
                    int i = file.showSaveDialog(this);
                    if (i != 1) {
                           File arquivo = file.getSelectedFile();
                           jTextFieldImagem.setText(arquivo.getAbsolutePath());
                           @SuppressWarnings("deprecation")
						Tesseract tess = Tesseract.getInstance();
                           tess.setLanguage("eng");
  
                           jTextAreaOCR.setText(tess.doOCR(arquivo));
  
                    }
             } catch (TesseractException e) {
                    JOptionPane.showMessageDialog(this, "Erro ao processar OCR");
                    e.printStackTrace();
             }
       }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FTesseractApp().setVisible(true);
            }
        });
    }
     
    // Declaração de variáveis - não modifique//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSelecionarImagem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaOCR;
    private javax.swing.JTextField jTextFieldImagem;
    // Fim da declaração de variáveis//GEN-END:variables
}